### ISSUE TITLE
Deprecated selector in `drag-drop-text\styles\drag-drop-text.less`

### ISSUE THREAD

**Issue by noseGoblin** [mark-hahn/drag-drop-text#7]
In `drag-drop-text\styles\drag-drop-text.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .drag-drop-text .region` => `atom-text-editor.editor .drag-drop-text .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by HAfsari** [comment]
not working

**Comment by keni8em** [comment]
Uploaded an update to the **_`drag-drop-text.less`_** file (#11). This bug can be marked as closed after merging my branch back with main and releasing the new version by @mark-hahn.

FYI: as per the error message, Atom implements a temporary fix for this issue but deprecation-cop still flags it.
My fix is simply just making the temporary fix permanent by removing **_`::shadow`_** from the code.

Issues #7, #9 & #10 are all for the same issue.

**Comment by keni8em** [comment]
Fixed in v1.0.0
